### ISSUE TITLE
ip lists?

### ISSUE THREAD

**Issue by somedevreally** [0xERR0R/blocky#1]
hello,

will list with ip's can be blocked?

`https://feodotracker.abuse.ch/downloads/ipblocklist.txt`

**Comment by cpressland** [comment]
This sounds like something that really needs to happen in a firewall like iptables rather than a DNS Server.

Blocking these IPs would require the DNS Server to do reverse lookups and store the results for future blocking, I imagine this would be a very expensive task with little benefit compared to just blocking the IPs at point of egress.

**Comment by dwmunster** [comment]
> Blocking these IPs would require the DNS Server to do reverse lookups and store the results for future blocking

While I agree in principle that blocking these at the firewall level would be a good solution, it would not be necessary to do reverse lookups. Before responding to a query with an IP, you could simply test that IP for inclusion in the blacklists.

**Comment by runningman84** [comment]
I also like the idea of checking whether the IP of a lookup is in some kind of blacklist

**Comment by 0xERR0R** [comment]
I also think, it could be an useful feature. List with IP can be handled as list with domain names.

**Comment by 0xERR0R** [comment]
Blocky checks response entries (CNAME and IP addresses A/AAAA) against the blacklists, see #3
