### ISSUE TITLE
Feature Request: Log the name of the used blacklist

### ISSUE THREAD

**Issue by felldo** [0xERR0R/blocky#1038]
It would be nice if it was possible to add the name of the used blacklist to the log(database). 
For example: `https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts` or `/path/to/blacklist` if using an own file

This then can be seen in the last queries panel in the Grafana dashboard, or a new panel can be created to only show blocked queries and where the blacklisted domain comes from. This would help to identify where false positives come from and makes it easier to report it to the appropriate organization.
![image](https://github.com/0xERR0R/blocky/assets/31566807/64973e1e-92bc-4f5d-93d5-df87a393c60f)

**Comment by kwitsch** [comment]
There was a discussion some time ago with the same request.
At the time it wasn't possible to determine if which blocklist included the domain if it was included in several blocklists.
With the current development version it should be possible to list all groups that block a domain.
Since each blocking group merges all including lists a per list outpu wouldn't be possible.

**Comment by felldo** [comment]
I can't look into the code and verify my statement(I'm not familiar with Go), but: Wouldn't it be possible with a second data structure to map each domain to their lists where they are included? Sure, this would increase the used memory and CPU usage as you would have to verify the correctness on each fetch of the list (or just completely rebuild the mapping once all lists are fetched), but IMO this would be a nice addition. 
There could be a new config with a default value to use the group name (as you now suggested) and the option to use the real location where the domain comes from.

**Comment by kwitsch** [comment]
Since the lists are aggregated your suggestion would increase the memory usage by a lot. Every list has to be kept in it's original form, the group aggregation and the relationship between them. Furthermore it would greatly increase the code complexity without a real benefit.

Why not use more groups?
You could group similar lists and use multiple list groups per client group.
