### ISSUE TITLE
Regex support in online lists and files. 

### ISSUE THREAD

**Issue by t-e-s-tweb** [0xERR0R/blocky#1103]
Does regex had to be inline only? Or can it be used from online lists or local txt. 
E.g in this format / /. Are these demiliters necessary in files too? 

I tried loading a file consisting of just domains and regex. The full was 2 million but only 1.3 million were being added. Probably regex were not loaded at all. 

Regex is in this format in txt file or online file 

/.*graph\.fbpigeon\.com/
/.*graph\.instagram\.com/
/.*api\.facebook\.com/
/.*star\..*\.facebook\.com/

Is it correct? Or does it only work inline in config file?

**Comment by 0xERR0R** [comment]
You can do both: use reges as inline definition or as a single line in a text file. Yes, delimiters are necessary, otherwise we can't distinguish between formats (for example "google.com" is a valid regex).

Your regex definitions look good, this should work. Do you have any warnings during the import process?

**Comment by ThinkChaos** [comment]
Closing in favor of #1090. You'll be happy to know I have a WIP for wildcards :)
