### ISSUE TITLE
Support file descriptor passing

### ISSUE THREAD

**Issue by Oppen** [0xERR0R/blocky#1119]
According to the docs, it seems only binding to network ports is allowed. This means you need to either:
- Run as root
- Run with network capabilities
- Use a second, non-privileged port and redirect requests to it with a different daemon

Besides the Unix socket option, there are protocols for passing bound sockets, so a different process can chainload the daemon with dropped privileges. This is a common pattern in daemontools descendants and systemd. There's a simple but flexible protocol proposed by systemd (and used by them and nosh) that allows passing several of them, so a single daemon can listen to several ports while running without privileges (including network capabilities).

Related: #1118

**Comment by ThinkChaos** [comment]
I'm not against this but I personally like unix sockets better since you're sure no firewall bug can make the service reachable somewhere you don't expect, and FS permissions are easier to manage than firewalls.

**Comment by ThinkChaos** [comment]
I'm not planning on implementing this, at least ATM, but it seems easy enough with off the shelve code.  
`dns.Server` ([docs](https://pkg.go.dev/github.com/miekg/dns#Server)) has fields to use existing listeners with this use case in mind: `Listener` and `PacketConn`.
And `go-systemd/activation` ([docs](https://pkg.go.dev/github.com/coreos/go-systemd/v22@v22.5.0/activation)) provides an abstraction to get systemd's listeners.

**Comment by Oppen** [comment]
> I'm not against this but I personally like unix sockets better since you're sure no firewall bug can make the service reachable somewhere you don't expect, and FS permissions are easier to manage than firewalls.

Those are not mutually exclusive though. You can open the unix socket and pass that fd too. I prefer that pattern because in some situations you can actually get away with implementing no socket opening at all (and I like my bug surface small), but retrofitting that part would be dumb here. It does help with persisting connections.

As with my other issue, if the PR is welcome, I'll give it a shot.

**Comment by ThinkChaos** [comment]
Sure, if you make a PR I can review :)

A couple pointers;
- we setup the sockets in `server/server.go`
- I think we need some config integration since we need to know what DNS protocol to expect for each socket (TCP/UDP is not enough to figure that out). The first that comes to mind is allowing a specific format in `config.ListenConfig`.  
  Something like `systemd:<name>` so you can do `ports: http: "systemd:blocky-http"`, and the the code in `server.go` checks for the `systemd:` prefix and treats that specially.  
  I didn't look too hard into it so this might not work/even be necessary.

Feel free to make a draft PR if you have questions about any of the details/want early feedback.
