### ISSUE TITLE
Deny response as function of question (type)

### ISSUE THREAD

**Issue by newrokor** [0xERR0R/blocky#1132]
Dear Blockers,

first of all: Congrats for your work, I really like blocky, and I run it as hobbyist on my small private server, directly connected to the internet on ports 53/853.

However, since some weeks I face a (also small) DDoS attack: several 100 questions/sec, all the same, from several thousand IPs (v4). For the moment, blocky's (blacklisted) responses come from cache, which is astonishingly fast, and the server can stand it easily right now. Of course, I run an IP-based firewall (iptables/ufw), but it would be very hard to defend it on this basis. I tried to limit the connections, however, I am not sure if this works properly. Still a lot of requests.

So, I read back and forth about the configuration of blocky, trying to make it behave like a firewall and deny certain traffic, based on question (type). I might have overlooked it, but is there an approach to do so within blocky? Is there a known configuration for iptables to defend such an attack? I am aware that this might not bring down the CPU load, however, it might distract the attacker.

Thanks in advance, newrokor

**Comment by kwitsch** [comment]
There is an option to filter question types: https://0xerr0r.github.io/blocky/v0.22/configuration/#filtering

This could indeed reduce the CPU load since the filter is applied before the cache lookup happens.

Blocky chains various functions and every request always is handed down the chain untill it is resolved. Therefore the CPU load should be reduced if an earlier function resolves it.

If you don't need hostname resolution(which would be unnecessary if not used locally) you could additionally enable an option to prevent these requests: https://0xerr0r.github.io/blocky/v0.22/configuration/#fqdn-only
This function is also at the beginning of the chain which could reduce the load further if these kind of requests occure.

**Comment by 0xERR0R** [comment]
Imho, opening 53 to the Internet is very dangerous. I would recommend ti use only dot/doh.

Regarding the ddos, i think it would make sense to implement rate limitingbin blocky.

So far, you can try to install a reverse proxy in front (traefik for example) and enable rate limiting there.

**Comment by kwitsch** [comment]
> Imho, opening 53 to the Internet is very dangerous. I would recommend ti use only dot/doh.
> 
> Regarding the ddos, i think it would make sense to implement rate limitingbin blocky.
> 
> So far, you can try to install a reverse proxy in front (traefik for example) and enable rate limiting there. 

Thanks for mentioning it.
Forgot the important part because I was focused on the technical stuff. 🤦‍♂️

**Comment by 0xERR0R** [comment]
Maybe we can also introduce some kind of ip/net whitelisting (accept requests only from subnet X)

**Comment by kwitsch** [comment]
If the request passes the internet router wouldn't it be always the router IP which does the request to blocky? 🤔

**Comment by 0xERR0R** [comment]
Yes, sure. But you can whitelist the ip range of your isp. Or block requests from some countries

**Comment by kwitsch** [comment]
Ok but blocky has to run on the router to get the original source IPs or am I missing something?

**Comment by 0xERR0R** [comment]
I mean if blocky runs on a public server. If you run it at home, it depends on your network configuration

**Comment by kwitsch** [comment]
Got it.

Was just trying to clarify the setup conditions to determine if this feature is interesting for many or more of a edge case.

**Comment by newrokor** [comment]
Unbelievable, guys. I did not expect so much answers within this short amount of time. Let me just comment shortly on your proposals, and give me some time to test some of them before returning with my experiences.

_Question type_ I see always ANY in the unwanted requests, so, in terms of a negative list, this would be easy for me. In terms of a positive list, of course, A and AAAA is clear to me, MX also, but unfortunately I am not fully through DNS, what further question types I should keep. Furthermore, if I read the configuration correctly, there will be an empty answer, so a sign of life to the attacker. Nevertheless, given the smaller CPU time, I will give this a try.

_Close port 53_ I tried this already, however, I did not document it properly. But if I remember it correctly, it did not change very much in terms of CPU load.

_Rate limiting_ The firewall of choice right now is ufw/iptables. I implemented a limit for 53/853 IP4/6 already, however, for reasons I did not understand, I saw by far more than the expected maximum of 12 requests/min within the standard adjustment of of ufw, for reasons I did not understand/analyze right now.

_WAN vs. LAN_ Shifting blocky to the LAN **is** an option for me, and it would not make that much difference for me right now. So, if the thing I see right now is the beginning of something worse, this is an option, giving up some of the original ideas. But as mentioned, its a hobby.

_Subnet whitelisting_ I also thought about that, however, I switch the ISP's IP on a nightly basis, and - to be honest - I have currently no idea about the subnets, which they use. Furthermore, mobiles outside of the LAN would need then another DNS server.

At the moment, it is annoyance not a problem, however, I learn that I need some countermeasures to run a blacklist DNS server stably in the WAN on the long run.

Thanks for the moment, I will keep you updated, but it will neeed soommme tiiimmmee.

newrokor

**Comment by newrokor** [comment]
Forgot that one:
_FQDN_ Questions switched from time to time within the last weeks, so my blacklist.txt became slightly bigger over time, however, the latest questions might pass this criterion.

And, last but not least, I have no idea about the purpose of that, besides trying to break something.

**Comment by kwitsch** [comment]
If you use blocky purely as DNS proxy you could filter most types except A, AAAA & CNAME.
A comprehensive list of record types can be found on Wikipedia: https://en.m.wikipedia.org/wiki/List_of_DNS_record_types
For a quick overview which DNS services there are and what records they use I recommend looking at the picture in the Wikipedia article.

A FQDN would be `google.de`.
`firewall` or `myserver` aren't FQDN.
If you use blocky in your internal network without a domain server to name your devices, enabling `FQDN only` would break it.
If you don't use it in such a scenario enabling it won't break anything.

Btw opening DNS or SMTP ports can be restricted via contract by your provider. There are ISPs in Germany that only allow it on commercial contracts.
This could lead to contract termination.

Thought you should know that since it happened to a friend of mine. 😅

**Comment by 0xERR0R** [comment]
relates to #1135

**Comment by newrokor** [comment]
Just as a short sign of life: @kwitsch Thank you for the infos. Currently, I restricted the questions to FQDN, and filtered the type ANY. Furthermore, I filtered a few IPs via firewall, and blacklisted a few DN, and out of the sudden the annoyance disappeared.

I will go on with the ideas mentioned above, however, I am pretty limited in time right now.

PS @kwitsch Thanks about the hint about the ISPs. As you mentioned it I remember such clauses in my internet past on webhosting. However, right now blocky runs on a VPS.
