### ISSUE TITLE
Reverse DNS does not work for local devices

### ISSUE THREAD

**Issue by schlamar** [0xERR0R/blocky#134]
The DNS resolver configured in clientLookup should be used for lookups in the local IP range. Right now reverse DNS lookups for local IPs doesn't work because they are forwarded to the upstream resolvers.

Workaround would be to configure the Fritz Box as the single upstream resolver.

**Comment by 0xERR0R** [comment]
Please share your config. I also have a fritzbox and I use the same clientresolver configuration as in readme.
Please try to set the log level to debug

**Comment by schlamar** [comment]
[blocky.log](https://github.com/0xERR0R/blocky/files/5991351/blocky.log)

[config.yml.txt](https://github.com/0xERR0R/blocky/files/5991355/config.yml.txt)

**Comment by 0xERR0R** [comment]
DNS resolver configured in "clientLookup" is used to map client's IP to name. This is necessary, to have "nice" client names in logs and grafana dashboard and of course to define client name based blocking rules. It worked in your case:
```
received response from conditional upstream answer= client_ip=192.168.181.20 client_names=LAPTOP-V2SVJD9H.fritz.box domain=fritz.box question=AAAA (rockrobo.fritz.box.) upstream=parallel upstreams 'upstream 'tcp+udp:192.168.181.1:53''
```

As you can see, your IP address 192.168.181.20 was mapped to name "LAPTOP-V2SVJD9H.fritz.box".

I see what you did: you tried to perform rDNS manually with: PTR 22.181.168.192.in-addr.arpa.

This is only possible if the upstream DNS resolver can answer this question. Since only FritzBox can answer this, you should ask the FritzBox directly (e.g. on Linux with `dig @192.168.181.1 ...`

**Comment by 0xERR0R** [comment]
You can also configure FritzBox as conditional resolver for rDNS:

```yml
conditional:
  mapping:
    fritz.box: udp:192.168.181.1
    168.192.in-addr.arpa: udp:192.168.181.1
```

**Comment by schlamar** [comment]
This sounds good, I'll try it tomorrow.


You can also configure FritzBox as conditional resolver for rDNS:

**Comment by schlamar** [comment]
Thanks, this works like a charm!
