### ISSUE TITLE
QNAME Minimization Support

### ISSUE THREAD

**Issue by starsoccer** [0xERR0R/blocky#1436]
More of a question then a request as I did a search and couldnt find any mention of it, but does blocky support QNAME minimization, as mentioned here, https://www.privacyguides.org/en/advanced/dns-overview/#what-is-qname-minimization

**Comment by ThinkChaos** [comment]
Hi, thanks for the good question!

As I understand it, QNAME minimization is relevant for recursive resolvers since they are the ones that contact the various DNS servers.  
Blocky sends a single question to one of your configured upstreams, so the minimization would need to happen on the upstream.

There might be other blocky features where we could apply the idea of minimization, so a quick survey of the code with that in mind would be interesting!

**Comment by starsoccer** [comment]
Ah good point, are there any plans to have blocky recursively resolve entries? Perhaps it would be more useful in that scenario then

**Comment by kwitsch** [comment]
There are currently no plans to add a recursive resolver functionality to blocky. 
There have been discussions about it in the past with the conclusion that this wouldn't be used by many users. 
If you want local recursive resolution it is best practice to run a separate DNS server for it and use it as upstream of blocky.
