### ISSUE TITLE
Initial CPU spike at start up, seems to be around requesting blocklists? 

### ISSUE THREAD

**Issue by dalanmiller** [0xERR0R/blocky#1549]
Reporting that I'm seeing some serious spikes at loadup. No hard data here just seems a bit over the top for making some HTTP requests to download the blocklists and loading those lists into memory. 

Is this something else happening during this time? Perhaps something gone awry? 

https://github.com/user-attachments/assets/d9272563-43a6-4d96-9a2a-0d46f06e79c0

**Comment by kwitsch** [comment]
Blocklists aren't simply loaded in memory. 
They are merged under your defined category and have to be processed in case of regex list. 
This can take some load. 
Additionally the processing is done in parallel(if not configured otherwise). 

It's likely that you can reduce the load by optimizing your config for your hardware. 
Decreasing the parallelism and watching the effect would be the first step.

**Comment by Teurg** [comment]
can you share the list?
