### ISSUE TITLE
disabling specialUseDomains not working

### ISSUE THREAD

**Issue by mapl** [0xERR0R/blocky#1613]
When setting rfc6762-appendixG to false, special domains are still blocked.

```
specialUseDomains:
  rfc6762-appendixG: false
```

Is this to be expected?

I want to forward **ANY** DNS Query to the Upstream DNS Server.

**Comment by ThinkChaos** [comment]
`rfc6762-appendixG` only controls [some of the special domain names](https://www.rfc-editor.org/rfc/rfc6762#appendix-G). I guess we can add a `enable` option so the whole blocking can be fully opted-out of.  
That option doesn't exist ATM because the RFCs say it's mandatory to block those TLDs. I guess if you have another internal DNS upstream of Blocky, and it blocks them, it's a valid use case.

**Comment by mapl** [comment]
Thanks, I created a PR for this #1614
