### ISSUE TITLE
blocky vs pi-hole

### ISSUE THREAD

**Issue by vkuznet** [0xERR0R/blocky#212]
Hi, I'm interested to know (and I hope I'm not alone) what are the similarities and differences between blocky and pi-hole. It would be nice to have such summary both in terms of functionality and performance. For instance, I would presume blocky will be easy to install on wrt based routers (assuming that it will fit within hardware constrains), it can run on different architectures (so it would be easier to port and run it natively, e.g. on MacOS). It would be nice to see some benchmarks too.

**Comment by 0xERR0R** [comment]
That is indeed a good question. Perhaps I should first explain the background to why this project was created:

I was a pi-hole user for a long time. However, a few things have increasingly bothered me. 
First, the architecture of pi-hole is IMHO not ideal. It uses a patched version of dnsmasq and some scripts around it. It works well in principle, but when things go wrong, troubleshooting is difficult.
Secondly, I missed some features, like defining blacklists per client, or custom DNS entries (this was possible with pihole, but not through the web interface, but through custom dnsmasq configuration).

I looked around and discovered adguard home. I liked the project: written in Go, fancy web interface. But at that time, not all features were available there either.

Since I wanted to learn Go myself (after 12 years of working in Java), I started the project. The goal was **not to** implement or replace pi-hole, but to create a simple tool without a web UI and complex configuration. Just following the KISS principle: simple file based configuration, which can be versioned with git, single self-contained binary. This tool is primary for people, who can analyse log files and can integrate this tool in the existing home network.

In the meantime, pi-hole and adguard home can both define client base lists and custom DNS entries, so there is no feature, which I would miss in these tools. Both projects are awesome and suitable for a wide audience. Blocky has prometheus support and is easier to configure. Some people use multi instance blocky in Kubernetes, since it is state-less and needs no database.

**Comment by vkuznet** [comment]
Thanks for explaining this. I suggest to put this summary into README of the project that people can easily find it and understand the intention. I'm also in favor of KISS and simple CLI tools, prometheus integration is obviously a big plus for those who knows its power. And, thanks for mentioning k8s aspect too.
