### ISSUE TITLE
Create cache for groups allows duplicates

### ISSUE THREAD

**Issue by joshuakraitberg** [0xERR0R/blocky#228]
https://github.com/0xERR0R/blocky/blob/b8aae26dcc76ccfc5667fa5c17f7df270732363c/lists/list_cache.go#L168

Say you have two links/files **in different groups** for you blacklist.

> \# file_one.txt
> thing.example.com

and 
> \# file_two.txt
> thing.example.com

Your cache will contain `thing.example.com` twice.  The entries in the cache should be a unique set.

As a followup, are these handled differently or are they functionally identical?  `0.0.0.0 thing.example.com` vs `thing.example.com`.

Based on the stats it also seems like comments and blank lines are cached.

**Comment by 0xERR0R** [comment]
Hey,

In in previous version, a cache was unique (basically it was converted to a set), but the memory consumption was not really good (peaks on reload). I removed the de-duplication, because the most list provider do already remove duplicates. If someone defines some double entries in its own blacklist, the memory overhead is negligible.

Regarding the question about the format: blocky can process a file with only domains or in a hosts format (uses always the last column, see https://github.com/0xERR0R/blocky/blob/fdbb87ac2cd4a5c70573a096f6c2977672df8121/lists/list_cache.go#L368).

Regarding the comments: All lines starting with `#` are skipped (https://github.com/0xERR0R/blocky/blob/fdbb87ac2cd4a5c70573a096f6c2977672df8121/lists/list_cache.go#L361). Do you have an example file for testing purposes?
