### ISSUE TITLE
Use a configuration folder

### ISSUE THREAD

**Issue by agneevX** [0xERR0R/blocky#268]
Currently, the config file needs to be mounted separately. Would be helpful if it could be mounted in a folder. The `/config` directory is commonly used.

```diff
  blocky:
    image: spx01/blocky
    container_name: blocky
    ports:
      - 127.0.0.1:2560:53/udp
    volumes:
+     /opt/appdata/blocky:/config
-     - type: bind
-       source: /opt/appdata/blocky/blocky.yml
-       target: /app/config.yml
```

**Comment by 0xERR0R** [comment]
Current implementation puts the binary in /app directory. Config should be in the same directory. If you want to change the directory, you can simply mount your config to /config/config.yaml and override the entrypoint:

```yaml
entrypoint: ["/app/blocky","--config","/config/config.yml"]
```

I would like to avoid changing this, because it would impact other things (like k8s helm chart, which is maintained by other people)

**Comment by agneevX** [comment]
Fair enough, thanks 👍
