### ISSUE TITLE
Use full qualified client name as group name

### ISSUE THREAD

**Issue by adamsewell** [0xERR0R/blocky#329]
I realize that blocky was made for a LAN environment but I'm testing with a few VPS's and using it with a handful of different locations that all have dynamic public IPs. These locations all have dynamic DNS names via noip.com. It looks like Blocky will do a rdns lookup, but that wouldn't help in my situation. I would it to actually do a regular 'ol lookup on a hostname like "xxxx.noip.com" and see if it matches the corresponding IP. Would this be something that could be added? Or maybe it already is and I'm just totally missing it. 

Thanks! I'm really digging this project.

**Comment by 0xERR0R** [comment]
Hey,
blocky "needs" a name of the client for blocking (to determine which lists should be used) and for logging purposes. rDNS will be performed if you define the `clientLookup.upstream` DNS server.
So your use case is: different client IPs (dynamic), but you want "nice" client names?

**Comment by adamsewell** [comment]
The usecase is basically this. Say a client has a dynamic dns name with noip. That name would be joebob.ddns.net which resolves to 192.111.111.xxx - So under clientGroupsBlock, I'd like to be able to use the joebob.ddns.net in place of the IP subnet or client hostname. That way, blocky could potentailly use the joebob.ddns.net to "authenticate" the requesting IP of 192.111.111.xxx to joebob.ddns.net and it's ruleset. If that makes sense.

**Comment by 0xERR0R** [comment]
ok, got it. With simple DNS query (port 53), there is only the IP address available, therefore you can either map ip to client name manually (in your case not possible, because dynamic IPs) or use rDNS to transform the IP to the host name. I'm not sure if your ddns provider has such rDNS resolver for own names. If yes, it work out of the box.

Another option would be to use DoT or DoH in blocky. In this case each client can pass own name with the request.

There is currently no way to resolve the name in clientGroupBlocks and match the result with request IP.

**Comment by adamsewell** [comment]
Right, that's kind of what I figured. Would this functionality be something you'd consider adding?

**Comment by 0xERR0R** [comment]
Yes, I think, it would be a nice additional lookup strategy. The lookup should be performed periodically and the result (IP addresss) should be cached.
