### ISSUE TITLE
Feature Request: `conditional.mapping` value to prevent upstream queries

### ISSUE THREAD

**Issue by ThinkChaos** [0xERR0R/blocky#367]
Hi,

Thanks for creating this project it's quite useful to me!

I'm using Blocky as the only DNS server on my router and would like to ensure no `.lan` (the domain I use for my lan) queries are leaked.
To do so I think the nicest would be to have a special value in `conditional.mapping` that means "only check `customDNS`".

Maybe something like this:
```yaml
conditional:
  mapping:
    lan: null
```

Related to implementation, I think adding a new resolver type that is chosen by `NewConditionalUpstreamResolver` when the list of `upstreams` is empty, which would be the case if the only value in the mapping was `null`.
This new resolver would unconditionally return a NXDOMAIN respone, similar to `nxDomainBlockHandler.handleBlock`.
An alternative to a new resolver type could be using a `BlockingResolver` with `BlockType == NXDOMAIN` that blocks everything. I haven't investigated this option much as adding a new type seems so simple and more explicit.

Is there a way to do this with existing config options I missed?
What do you think about my plan for implementation? I'd be happy to write the code myself and open a PR.

**Comment by 0xERR0R** [comment]
Hi,

I assume, you are using `customDNS.mapping` to define your devices within the .lan domain, right? If yes, you can just define a custom blacklist entry as regex to block all ".lan" queries, something like "/^.*\.lan$/". Since blocking resolver is after the custom resolver, it will block all *.lan if the query was not resolved by customDnsResolver.
