### ISSUE TITLE
Dynamically adding config

### ISSUE THREAD

**Issue by geekscrapy** [0xERR0R/blocky#408]
I was wondering if it was possible to change the config at runtime?
I'm interested in using blocky to redirect DNS requests to upstream servers based on the source IP. The source IPs aren't statically defined.

**Comment by 0xERR0R** [comment]
Hi,
no, config change at runtime is not possible, we had an issue for this feature(#7). This is a complex topic (validation, error handling etc.) and the way to go is to restart the process/container on configuration change. This is usually the way recommended for 12factor apps.

Regarding your request: yes, this is possible. You can define different upstream DNS servers per client(group): #81 

If client IPs are dynamic, you must provide a name for each client (either rDNS or you have to use DoT/DoH).

**Comment by kwitsch** [comment]
If you deploy multiple blocky instances in docker an seamless update to a new configuration can be done with [update_config](https://docs.docker.com/compose/compose-file/compose-file-v3/#update_config) and [rollback_config](https://docs.docker.com/compose/compose-file/compose-file-v3/#rollback_config).
I use this for a few months now without problems.

If your DNS server provides rDNS, the mapping can be done through hostnames.
This option is activated most of the time in consumer grade hardware solutions like FritzBoxes for example.

Commercial grade hardware solutions(like Ubiquiti & Omada) often lack this feature.
I build a [workaround](https://github.com/0xERR0R/blocky/issues/245#issuecomment-1008354400) for that.
It's still in testing due to lack of time on my part.

**Comment by geekscrapy** [comment]
Thank you both for your help! I've decided that dynamically changing config isn't really an issue when I can restart a docker instance so quickly, and with x_config as @kwitsch suggested.
