### ISSUE TITLE
Update binary from cli

### ISSUE THREAD

**Issue by broizter** [0xERR0R/blocky#52]
Would be nice to be able to update the binary from the cli, something like this for example;

```
blocky update
```

Bonus points if we could execute a command depending on if the update succeeded or not. For example I run Blocky from a systemd service file I made so I would wanna restart that if the update succeded. I guess you could configure that in the .yml file.

**Comment by 0xERR0R** [comment]
Auto update is a complex process: if new version has new configuration properties, there must be always a default value. Or configuration file must be versioned. If update fails, last version should be restored, otherwise you will lost your DNS resolver and this is a very critical component in the network. I would always prefer to update critical components manually and check if configuration file  must be updated too.
Did you try the docker image for blocky? This make updating easier (just docker pull).

**Comment by broizter** [comment]
I agree with all your concerns regarding auto update, but the risks are something I'm personally prepared to live with. I was hoping to avoid docker for... reasons but I will consider it at least.

**Comment by 0xERR0R** [comment]
I will close this issue, this topic is out of scope of this project and will introduce a lot of complexity. I think, the right way to achieve this (if you don't want to use docker), would be to create a OS specific package (DEB/RPM, AUR (archlinux), snap, Windows installer ...). This would create all OS dependent configurations and services (autostart, firewall etc).

**Comment by whalehub** [comment]
@broizter I'll be adding support for this application in the next update of `ginstall.sh`. 👍

**Comment by broizter** [comment]
@whalehub Awesome!

**Comment by whalehub** [comment]
@broizter I just published `ginstall.sh` [v1.3.0](https://github.com/whalehub/ginstall.sh/releases/tag/v1.3.0) with support for Blocky. 🎉
