### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by mapl** [0xERR0R/blocky#59]
The current Blocky code is unable to complile on windows due to some *nix specific code like

https://github.com/0xERR0R/blocky/blob/0ec6c8af9c5e79863d4d97e5f94927f71879c4ce/resolver/query_logging_resolver.go#L46

and some more.
Having these parts rewritten to os agnostic code, Blocky would join the Windows family.

**Comment by 0xERR0R** [comment]
I will try to compile the binary for windows and fix the errors. The main purpose for blocky was to run on raspberry pi (and other low power devices) and as docker image. But go supports windows and it would be indeed good to eliminate all platform dependent code

**Comment by mapl** [comment]
Very cool! :) After some minor tweaks, Ive got it running. 

Next nice feature would be to install it as Windows Service. 

There is a good lib for that https://github.com/kardianos/service

Wonderful Caddy Server is also using the same package

https://github.com/hacdias/caddy-service

**Comment by 0xERR0R** [comment]
Cross-compiling for Windows works now. Signals USR1 and USR2 (print stats and config) would not work (Windows supports only Interrupt and Kill). Regarding other points (Installation as Service): this is out of scope of this project, because there are so many different OS and installation ways (Windows service, DEB/RPM for Linux, Snap, AUR for Arch, PPA for Ubuntu, ...). Therefore, only binary and docker image are provided. Other user created a helm chart (linked in Readme) for Kubernetes, he maintains this configuration.

**Comment by mapl** [comment]
Thank you
