### ISSUE TITLE
prometheus metrics for queries

### ISSUE THREAD

**Issue by maltechx** [0xERR0R/blocky#71]
It would be nice to have a metric of the top queries per domain so you know if something weird is blocked or not blocked.
- top queries per domain
- label if blocked or not

**Comment by 0xERR0R** [comment]
By design, prometheus uses numbers as values for metrics. Those metrics can be extended with labels. Both (metrics and labels) should be used for limited set of data. Since a domain name is not limited, there would be a cartinality problem, prometheus will store each domain for a certain amount of time (defined as retention time, default 2 weeks). See here for further information: https://www.robustperception.io/cardinality-is-key

Did you try to use the statistic output (SIGUSR2 signal)? In this output you can see the top queried and blocked domains

**Comment by maltechx** [comment]
I never thought about limiting that. It makes sense to me, but the you have the same thing with `blocky_query_total`.
I didn't know that this output existed, is this documented somewhere?
If you run blocky in docker you need to send the signal to the container and then take a look into the logs. Maybe ist possible to get this information via api call?
But so far I like the project a lot. For me its a better solution than running a Pihole.

**Comment by 0xERR0R** [comment]
Regarding `blocky_query_total`: Yes, client name is not limited, but normally, you would have a limited number of clients in your local network. If client number is huge (>100), this could became a problem.
Statistic output is documented in the readme (really short), statistic output via REST API or directly wia HTTP (output direct in browser) would be indeed nice.

**Comment by broizter** [comment]
Was this ever implemented?

**Comment by 0xERR0R** [comment]
No, see my last comment
