### ISSUE TITLE
Allow encrypted dns without bootstrap

### ISSUE THREAD

**Issue by devipasigner** [0xERR0R/blocky#842]
Hello, some dns providers allow you use to use encrypted dns via the direct ip without the need to resolve a domain name. For my configuration if I put “tcp-tls:9.9.9.9” it won’t work without a bootstrap. And bootstrap does not work if I put “tcp-tls:9.9.9.9”. So you should allow bootstrap dns to be encrypted without IPS too.

**Comment by ThinkChaos** [comment]
> if I put “tcp-tls:9.9.9.9” it won’t work without a bootstrap

This is working fine for me. Is your system resolver working? In other words, can the machine where blocky runs do DNS lookups without blocky?

Can you also give me more information:
- config
- blocky version
- logs with `logLevel: trace`

> bootstrap does not work if I put “tcp-tls:9.9.9.9”

This was fixed by e47a8b7f609bea5f6cc14e96155c3d1b8f78d54d, which will be part of the next release.
