### ISSUE TITLE
Update Documentation for Helm Charts

### ISSUE THREAD

**Issue by MegaShinySnivy** [0xERR0R/blocky#847]
TrueCharts is no longer supporting or leaving available it's helm charts for use outside of SCALE, meaning the current chart is now defunct. I would recommend looking at https://github.com/geek-cookbook/charts/tree/main/charts/stable/blocky for a supported helm chart.

**Comment by MegaShinySnivy** [comment]
Not stale, bot.

**Comment by ThinkChaos** [comment]
I don't think the chart is defunct:/unsupported it's still in the [docs](https://truecharts.org/charts/enterprise/blocky/) and has [regular commits](https://github.com/truecharts/charts/commits/master/charts/enterprise/blocky).  
The links in blocky's docs are broken though, so we should fix that.

The repo you linked seems to have a lot of extra commits that could be useful, but I think they should contribute that back to TrueCharts to benefit others instead of us recommending a fork.

I don't use any of this so this could all be very wrong/misinformed.

**Comment by MegaShinySnivy** [comment]
When I opened this issue, Truecharts had removed all of their charts in favor of only offering native charts, but they appear to have added them back. TrueCharts also, in my opinion, provides an inferior helm chart, but I am also heavily biased. The one linked is based on k8s-at-home, not TrueCharts.

**Comment by zc-devs** [comment]
I've tried TrueCharts' chart recently.

1. They use old options in [configmap.yaml](https://github.com/0xERR0R/blocky/files/14576817/configmap.yaml.txt)
2. They use unnecessary capabilities, env vars, mounts and so on in [deployment.yaml](https://github.com/0xERR0R/blocky/files/14576868/deployment.yaml.txt)
3. And cherry on the cake: they require [cloudnative-pg](https://truecharts.org/manual/SCALE/guides/common-errors/#operator-cloudnative-pg-has-to-be-installed-first) and [prometheus-operator](https://truecharts.org/manual/SCALE/guides/common-errors/#operator-prometheus-operator-has-to-be-installed-first) to be installed in your cluster. Even though I just wanted `helm template ./blocky -f values.yaml > blocky.yaml`. Had to remove a couple of files and lines of code from their template to get rid of errors.

That was not so convenient, softly speaking. Maybe removing TrueCharts from documentation at all is better than mentioning.

**Comment by MegaShinySnivy** [comment]
I would agree with this, using either App-Template or avoiding mentioning it at all would be better IMO

**Comment by ThinkChaos** [comment]
I opened PR #1398 to mention the chart only for TrueNAS. Please let me know if that's seems good for you.
