### ISSUE TITLE
Strange error when using blocky as an upstream DoH server of another blocky instance

### ISSUE THREAD

**Issue by PeterDaveHello** [0xERR0R/blocky#876]
I'm getting this error, which `xxx.xxx.xxx.xxx` is the IP address and `yyyyy` is the port number, when I use blocky as an upstream DoH server of another blocky instance:

The server side:
> http: TLS handshake error from xxx.xxx.xxx.xxx:yyyyy: EOF 

The client side:
> ERROR server: error on processing request:resolution was not successful, used resolvers 'upstream 'https://example.dommain.a/dns-query'' and 'upstream 'https://example.dommain.b/dns-query'' errors: [can't resolve request via upstream server https://[xxx.xxx.xxx.xxx]:443/dns-query: can't perform https request: Post "https://[xxx.xxx.xxx.xxx]:443/dns-query": dial tcp [xxx.xxx.xxx.xxx]:443: connect: cannot assign requested address can't resolve request via upstream server https://xxx.xxx.xxx.xxx:443/dns-query: can't perform https request: Post "https://xxx.xxx.xxx.xxx:443/dns-query": context deadline exceeded (Client.Timeout exceeded while awaiting headers)]

Would like to discuss how to debug this situation and what the problem might be 😅

**Comment by ThinkChaos** [comment]
It seems like both sides are waiting for the error to send data:
- server complains about `EOF`
- client says "Timeout exceeded while awaiting headers"

Can you curl the upstream from where the client runs?

Another part of the client error that seems important is "connect: cannot assign requested address".  
Apparently it can't get an address to contact the upstream? But since the upstream still receives data, I'm not sure how accurate that message is.

**Comment by PeterDaveHello** [comment]
> Can you curl the upstream from where the client runs?

Yes, without problems 😅 

> Another part of the client error that seems important is "connect: cannot assign requested address". Apparently it can't get an address to contact the upstream? But since the upstream still receives data, I'm not sure how accurate that message is.

Not sure if #834 is related? Similar error message shows up.

**Comment by ThinkChaos** [comment]
Is this still relevant? Did you test since #834 was fixed?

**Comment by PeterDaveHello** [comment]
I will test it soon.
