### ISSUE TITLE
[Feature request] Option to renew prefetch track time window periodically

### ISSUE THREAD

**Issue by alpominth** [0xERR0R/blocky#886]
In my tests, Block performs prefetching only one time per session when a hostname is queried and it's cached.

Here I had to adjust Blocky in systemd using this option in the .service file:

```
[...]
[Service]
RuntimeMaxSec=2h
[...]
```

An option in Blocky to do that automatically would be a good idea, at least it would be useful when using via shell scripts.

**Comment by kwitsch** [comment]
Prefetching is done according to the configured threshold and timeframe.
Therefore there has to be some kind of demand for it to kick in.

If you want a response to stay in cache the simplest solution would be to periodically query it.

If the demand won't drop it says prefetched in cache forever. 

I do exactly that to keep some DNS responses in cache over the weekend.

**Comment by kwitsch** [comment]
I only activated prefetching without changing the thresholds and use a [Docker container](https://github.com/kwitsch/docker-DnsCacheRefresh) to query the domains i want to stay cached every 10 minutes.

In your configuration there has to be more than one query in a 7 minute timeframe to activate prefetching but your minimal cache time is way above.

It looks to me that your timings are off.
Are you sure you want `minTime: 86400m` and `cacheTimeNegative: 10080m`?

**Comment by kwitsch** [comment]
Durations can be defined in various ways ("s", "m", "h", "d", "w", "y").
Same duration as "7d" would be more readable. 😉

If you want to permanently block a domain "7d" for cacheTimeNegative is ok but can cause trouble if for example a domain is removed from a block list. Clients would recognize this change days later even if you refresh the block list every hour.

Same goes for minTime if the IP changes behind the domain.
Using a dynamic DNS domain that changes it's IP every hour this would be rather unusable. I had trouble using some services with higher values of minTime.

Got my best results with minTime of a few minutes and the default prefetching config.

But as always: it depends on your setup and goal 😅

**Comment by ThinkChaos** [comment]
I don't think `SIGHUP` does anything to blocky.

Prefetching happens when the entry was already queried and cached, and its cache is expiring. The name might be a bit misleading: it's more of a "pre-refresh".  
Every cached entry is checked on expiry for "should I prefetch this": blocky deos the prefetch if the entry was queried `> prefetchThreshold` in the last `prefetchExpires` duration.

So for your config, you'd see blocky making the request in Wireshark 1545s (`startpage.com`'s TTL) after it was first queried, if you queried it more than 1 (`prefetchThreshold`) times in the 20s (`prefetchExpires`) preceding the expiration.  

Here's a small script (untested) of what needs to happen for the prefetch to work as you configured it:
```bash
dig startpage.com
sleep $((1545-20))
for ((i=0;i<=1;i++)); do dig startpage.com; done
```

Hopefully that helps clear up how this works for you.

I personally don't use this feature but think it's confusing, and the options don't seem to align with the common use case, as evidenced by @kwitsch's second container setup.  
See also #772 where I brought up something else I find confusing about how this works.

**Comment by 0xERR0R** [comment]
> 
> Ok, I thought Blocky re-fetch the queries before their expiring.
> 

Refresh (querying again to refresh the cache) happens just in the moment as the entry expires. That means, if you query for a prefetched domain X just in the time as its TTL is expired, I'll get the latest cached result with TTL 0. In the background, the cache entry will be refreshed.
