### ISSUE TITLE
Lists using ! for comments are now basically ignored

### ISSUE THREAD

**Issue by mjwhitta** [0xERR0R/blocky#956]
As an example: https://big.oisd.nl.

Looks like AdBlock uses `!` for comments. I haven't been able to find where this change happened. Version v0.20 works. Version v0.21 logs warnings about errors (not intuitive) then logs an actual error saying the list had too many errors. Since the comments are at the top of the file, this causes the whole list to be ignored. If `startStrategy` is `failOnError`, the container bails out. Additionally, it looks like wildcards are no longer supported? Below are examples of v0.20 and v0.21 logs:

v0.20 log:

```
homelab-blocky-1  | [2023-03-27 13:04:52]  INFO list_cache: starting download link=https://big.oisd.nl
homelab-blocky-1  | [2023-03-27 13:04:59]  INFO list_cache: file imported count=284619 source=https://big.oisd.nl
```

```
$ grep -i "error" v0.20.log
homelab-blocky-1  | [2023-03-27 13:05:03]  INFO server:      FailStartOnListError = false
```

My `startStrategy` is `failOnError`, so not sure why that says false.

v0.21 log:

```
homelab-blocky-1  | [2023-03-27 13:20:49]  WARN list_cache: parse error: line 122: 2 errors occurred:
homelab-blocky-1  | 	* invalid domain name: awsdns-cn-*.cn
homelab-blocky-1  | 	* invalid ip: awsdns-cn-*.cn
homelab-blocky-1  |
homelab-blocky-1  | , trying to continue count=116 source=inline block (item #0 in group)
homelab-blocky-1  | [2023-03-27 13:20:49] ERROR list_cache: parse error: line 122: too many parse errors count=116 source=inline block (item #0 in group)
homelab-blocky-1  | [2023-03-27 13:20:49]  INFO list_cache: starting download link=https://big.oisd.nl
homelab-blocky-1  | [2023-03-27 13:20:50]  WARN list_cache: parse error: line 1: 2 errors occurred:
homelab-blocky-1  | 	* invalid domain name: [Adblock
homelab-blocky-1  | 	* invalid ip: [Adblock
homelab-blocky-1  |
homelab-blocky-1  | , trying to continue count=0 source=https://big.oisd.nl
homelab-blocky-1  | [2023-03-27 13:20:50]  WARN list_cache: parse error: line 2: 2 errors occurred:
homelab-blocky-1  | 	* invalid domain name: !
homelab-blocky-1  | 	* invalid ip: !
homelab-blocky-1  |
homelab-blocky-1  | , trying to continue count=0 source=https://big.oisd.nl
homelab-blocky-1  | [2023-03-27 13:20:50]  WARN list_cache: parse error: line 3: 2 errors occurred:
homelab-blocky-1  | 	* invalid domain name: !
homelab-blocky-1  | 	* invalid ip: !
homelab-blocky-1  |
homelab-blocky-1  | , trying to continue count=0 source=https://big.oisd.nl
homelab-blocky-1  | [2023-03-27 13:20:50]  WARN list_cache: parse error: line 4: 2 errors occurred:
homelab-blocky-1  | 	* invalid domain name: !
homelab-blocky-1  | 	* invalid ip: !
homelab-blocky-1  |
homelab-blocky-1  | , trying to continue count=0 source=https://big.oisd.nl
homelab-blocky-1  | [2023-03-27 13:20:50]  WARN list_cache: parse error: line 5: 2 errors occurred:
homelab-blocky-1  | 	* invalid domain name: !
homelab-blocky-1  | 	* invalid ip: !
homelab-blocky-1  |
homelab-blocky-1  | , trying to continue count=0 source=https://big.oisd.nl
homelab-blocky-1  | [2023-03-27 13:20:50]  WARN list_cache: parse error: line 6: 2 errors occurred:
homelab-blocky-1  | 	* invalid domain name: !
homelab-blocky-1  | 	* invalid ip: !
homelab-blocky-1  |
homelab-blocky-1  | , trying to continue count=0 source=https://big.oisd.nl
homelab-blocky-1  | [2023-03-27 13:20:50] ERROR list_cache: parse error: line 6: too many parse errors count=0 source=https://big.oisd.nl
```

```
$ grep -i "error" v0.21.log | wc -l
137
```

Same exact config between versions.

**Comment by ThinkChaos** [comment]
Adblock syntax is not supported (see #950 for request to support) and the number of parsed hosts in v0.20 is pretty much a lie.  
Here's how v0.20 interprets the first couple lines of that list:
![image](https://user-images.githubusercontent.com/4761135/228108245-ccf3e016-f63b-4fda-8426-e6a93d4f57a1.png)

The list was "parsed" but its content was not be used properly: all those entries we used literally as domains and would never match anything.  
v0.21 validates the contents better, warns on the first 5 parse errors, and bails on the 6th error.  
Basically the list failing to parse isn't a bug, it's a feature :smile:. The bug was blocky loading an invalid list without complaining.

For now you can comment that list in your config, and no functionality will be lost compared to v0.20.

> Additionally, it looks like wildcards are no longer supported?

They never have, and were also being interpreted incorrectly as a domain with `*` in it. You should use a regex.  
For example: `awsdns-cn-*.cn` should be `/awsdns-cn-[^.]+*\.cn/`

> My startStrategy is failOnError, so not sure why that says false.

This is a bug: we're logging the deprecated `failStartOnListError`. We should log `startStrategy` instead.  
I'll make a PR for that.
