### ISSUE TITLE
Support international domain names in lists (IDNA)

### ISSUE THREAD

**Issue by ThinkChaos** [0xERR0R/blocky#961]
See https://github.com/0xERR0R/blocky/discussions/960

Example list: `https://raw.githubusercontent.com/rahilpathan/pihole-whitelist/main/1.LowWL.txt`  
Fix idea: use the idna module's [ToASCII](https://pkg.go.dev/golang.org/x/net/idna#Profile.ToASCII) to convert those domains to their punycode representation which is what blocky should receive from clients.

**Comment by 0xERR0R** [comment]
I changed it from bug to feature 😄 

We support currently lists in hosts file format or plain domain names. A particular domain name may contain only letters, numbers (and some special characters like hyphen). List maintainers should validate its content and use only valid names.

It is a very good idea to convert list content on-the-fly to punycode if necessary. Since user can also create his own lists or use inline definitions. 👍
